package ${daoPackage};

import java.util.List;

import org.apache.ibatis.annotations.Param;

import ${modelPackage}.${modelClsName};
import com.sales.util.pager.helper.PageInfo;

public interface ${daoClsName} {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_user
     *
     * @mbg.generated
     */
    int insert(${modelClsName} record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_user
     *
     * @mbg.generated
     */
    int insertSelective(${modelClsName} record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_user
     *
     * @mbg.generated
     */
    ${modelClsName} selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(${modelClsName} record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(${modelClsName} record);        
    
    /**
     * @param record
     * @param page
     * @return
     */
    List<${modelClsName}> selectList(@Param("model") ${modelClsName} record,@Param("page") PageInfo page);
}