<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN" "http://mybatis.org/dtd/mybatis-3-mapper.dtd">
<mapper namespace="${daoPackage}.${daoClsName}">
  <resultMap id="BaseResultMap" type="${modelPackage}.${modelClsName}">
    <!--
      WARNING - @mbg.generated
      This element is automatically generated by MyBatis Generator, do not modify.
    -->
    
    <#list metaTbl.colList as metaCol>
    	<!-- // ${metaCol.columnComment} -->
    	<#if (metaTbl.primaryKey?default('id') == metaCol.columnName)><#--jdbcType="${metaCol.jdbcType}"-->
    	<id column="${metaCol.columnName}" property="${metaCol.propertyName}" />
		<#else>
		<result column="${metaCol.columnName}" property="${metaCol.propertyName}" />
		</#if>
    </#list>
    
    <#list metaTbl.colList as metaCol>
    <#if metaCol.refPropertyName??>
    <association property="${metaCol.refPropertyName}" javaType="${modelPackage}.${metaCol.referencedTableClsName}">
    	<id column="${metaCol.columnName}" property="id"/>
    	<result column="${metaCol.refPropertyName}_id" property="id" />
    	<result column="${metaCol.refPropertyName}_${metaCol.refLabelColumnName}" property="${metaCol.refLabelPropertyName}" />
    </association>
    
    </#if>
	</#list>
    
  </resultMap>
  
  <sql id="Base_Column_List">
    <!--
      WARNING - @mbg.generated
      This element is automatically generated by MyBatis Generator, do not modify.
    -->
    
    <#list metaTbl.colList as metaCol>
    	<#if metaCol.refPropertyName??>
    	${metaCol.refPropertyName}.id AS ${metaCol.refPropertyName}_id, 
		${metaCol.refPropertyName}.${metaCol.refLabelColumnName} as ${metaCol.refPropertyName}_${metaCol.refLabelColumnName},
    	</#if>
    	o.${metaCol.columnName}<#if (metaCol_has_next)>, </#if>
    </#list>
	
  </sql>
  
  <sql id="Base_From_Tbl">
  	from ${metaTbl.tableName} o
		<#list metaTbl.colList as metaCol>
	    	<#if metaCol.refPropertyName??>
	    LEFT JOIN ${metaCol.referencedTableName} ${metaCol.refPropertyName} ON (o.${metaCol.columnName} = ${metaCol.refPropertyName}.id)
	    	</#if>
		</#list>		
  </sql>
  
  <select id="selectByPrimaryKey" parameterType="java.lang.Long" resultMap="BaseResultMap">
    <!--
      WARNING - @mbg.generated
      This element is automatically generated by MyBatis Generator, do not modify.
    -->
    select 
    <include refid="Base_Column_List" />
    <include refid="Base_From_Tbl" />
    where o.${metaTbl.primaryKey} = ${"#{"+metaTbl.primaryKeyProperty+"}"}
  </select>
  
  <delete id="deleteByPrimaryKey" parameterType="java.lang.Long">
    <!--
      WARNING - @mbg.generated
      This element is automatically generated by MyBatis Generator, do not modify.
    -->
    delete from ${metaTbl.tableName}
    where ${metaTbl.primaryKey} = ${"#{"+metaTbl.primaryKeyProperty+"}"}
  </delete>
  
  <insert id="insert" parameterType="${modelPackage}.${modelClsName}">
    <!--
      WARNING - @mbg.generated
      This element is automatically generated by MyBatis Generator, do not modify.
    -->
    insert into ${metaTbl.tableName} (
      <#list metaTbl.colList as metaCol>
      ${metaCol.columnName}<#if (metaCol_has_next)>, </#if>
	  </#list>
      )
    values (
      <#list metaTbl.colList as metaCol>
      ${"#{"+metaCol.propertyName+"}"}<#if (metaCol_has_next)>, </#if>
	  </#list>	 
      )
  </insert>
  
  <insert id="insertSelective" parameterType="${modelPackage}.${modelClsName}">
    <!--
      WARNING - @mbg.generated
      This element is automatically generated by MyBatis Generator, do not modify.
    -->
    insert into ${metaTbl.tableName}
    <trim prefix="(" suffix=")" suffixOverrides=",">
    <#list metaTbl.colList as metaCol>
      <if test="${metaCol.propertyName} != null">
        ${metaCol.columnName},
      </if>
	</#list>
    </trim>
    <trim prefix="values (" suffix=")" suffixOverrides=",">
    <#list metaTbl.colList as metaCol>
      <if test="${metaCol.propertyName} != null">
        ${"#{"+metaCol.propertyName+"}"},
      </if>
	</#list>
    </trim>
  </insert>
  
  <update id="updateByPrimaryKeySelective" parameterType="${modelPackage}.${modelClsName}">
    <!--
      WARNING - @mbg.generated
      This element is automatically generated by MyBatis Generator, do not modify.
    -->
    update ${metaTbl.tableName}
    <set>
      <#list metaTbl.colList as metaCol>
      <if test="${metaCol.propertyName} != null">
      	${metaCol.columnName} = ${"#{"+metaCol.propertyName+"}"},
      </if>
	 </#list>	
    </set>
    where ${metaTbl.primaryKey} = ${"#{"+metaTbl.primaryKeyProperty+"}"}
  </update>
  
  <update id="updateByPrimaryKey" parameterType="${modelPackage}.${modelClsName}">
    <!--
      WARNING - @mbg.generated
      This element is automatically generated by MyBatis Generator, do not modify.
    -->
    update ${metaTbl.tableName}
    set 
	 <#list metaTbl.colList as metaCol>
	 	<#if !((metaTbl.createDateCol?? && metaTbl.createDateCol.columnName== metaCol.columnName) ||(metaTbl.createUserIdCol?? && metaTbl.createUserIdCol.columnName== metaCol.columnName)) >
      ${metaCol.columnName} = ${"#{"+metaCol.propertyName+"}"}<#if (metaCol_has_next)>, </#if>
		</#if>
	 </#list>
    where ${metaTbl.primaryKey} = ${"#{"+metaTbl.primaryKeyProperty+"}"}
  </update>
  
  <select id="selectList" resultMap="BaseResultMap"
		parameterType="java.util.Map">
		<!-- WARNING - @mbggenerated This element is automatically generated by 
			MyBatis Generator, do not modify. -->
		select
		<include refid="Base_Column_List" />
		<include refid="Base_From_Tbl" />
		<where>
			<#list metaTbl.colList as metaCol>
			
			<#if metaCol.javaTypeSimpleName=='String'>
			<if test="model.${metaCol.propertyName} != null and model.${metaCol.propertyName} != ''">
				<trim prefix="AND (" suffix=")" suffixOverrides="AND | OR">
					o.${metaCol.columnName} like CONCAT('%','${"${"+"model."+metaCol.propertyName+"}"}','%')
				</trim>
			</if>
			<#else>
			<if test="model.${metaCol.propertyName} != null">
				<trim prefix="AND (" suffix=")" suffixOverrides="AND | OR">
					o.${metaCol.columnName} = ${"#{"+"model."+metaCol.propertyName+"}"}
				</trim>
			</if>
			</#if>
			</#list>
		</where>
	</select>
	
</mapper>