<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN" "http://mybatis.org/dtd/mybatis-3-mapper.dtd">
<mapper namespace="${daoPackage}.${daoClsName}">
  <resultMap id="BaseResultMap" type="${modelPackage}.${modelClsName}">
    <!--
      WARNING - @mbg.generated
      This element is automatically generated by MyBatis Generator, do not modify.
    -->
    
    <#list metaTbl.colList as metaCol>
    	
    	<#if (metaTbl.primaryKey?default('id') == metaCol.columnName)>
    	<id column="${metaCol.columnName}" jdbcType="${metaCol.dataType}" property="${metaCol.propertyName}" />
		<#else>
		<result column="${metaCol.columnName}" jdbcType="${metaCol.dataType}" property="${metaCol.propertyName}" />
		</#if>
    	
    </#list>
    <!--
    <association property="userTypeRef" javaType="com.sales.model.system.SysParameter">
    	<id column="user_type" property="id"/>
    	<result column="userTypeRef_id" property="id" />
    	<result column="userTypeRef_param_val" property="paramVal" />
    </association>
    -->
  </resultMap>
  <sql id="Base_Column_List">
    <!--
      WARNING - @mbg.generated
      This element is automatically generated by MyBatis Generator, do not modify.
    -->
	o.id, o.user_id, o.user_name, o.password, o.status, o.create_user_id, o.update_user_id, o.create_date, 
    o.update_date, o.last_login_date, o.description, o.organization_id, o.user_type, o.auth_type, 
    o.emp_entry_time, o.emp_leave_time, o.emp_status, o.tel,
    userTypeRef.id AS userTypeRef_id, userTypeRef.param_val as userTypeRef_param_val,
    empStatusRef.id AS empStatusRef_id,empStatusRef.param_val AS empStatusRef_param_val,
    organizationIdRef.id as organizationIdRef_id,organizationIdRef.name as organizationIdRef_name,organizationIdRef.code as organizationIdRef_code,
    authTypeRef.id AS authTypeRef_id,authTypeRef.param_val AS authTypeRef_param_val
    <!-- id, user_id, user_name, password, status, create_user_id, update_user_id, create_date, 
    update_date, last_login_date, description, organization_id, user_type, auth_type, 
    emp_entry_time, emp_leave_time, emp_status, tel -->
  </sql>
  <sql id="Base_From_Tbl">
  	from t_sys_user o
		LEFT JOIN t_sys_parameter userTypeRef ON (o.user_type = userTypeRef.id)
		LEFT JOIN t_sys_parameter empStatusRef ON (o.emp_status = empStatusRef.id)
		LEFT JOIN t_organization organizationIdRef ON (o.organization_id = organizationIdRef.id)
		LEFT JOIN t_sys_parameter authTypeRef ON (o.auth_type = authTypeRef.id)
  </sql>
  <select id="selectByPrimaryKey" parameterType="java.lang.Long" resultMap="BaseResultMap">
    <!--
      WARNING - @mbg.generated
      This element is automatically generated by MyBatis Generator, do not modify.
    -->
    select 
    <include refid="Base_Column_List" />
    <include refid="Base_From_Tbl" />
    where o.id = #{id,jdbcType=BIGINT}
  </select>
  <delete id="deleteByPrimaryKey" parameterType="java.lang.Long">
    <!--
      WARNING - @mbg.generated
      This element is automatically generated by MyBatis Generator, do not modify.
    -->
    delete from t_sys_user
    where id = #{id,jdbcType=BIGINT}
  </delete>
  <insert id="insert" parameterType="com.sales.model.system.SysUser">
    <!--
      WARNING - @mbg.generated
      This element is automatically generated by MyBatis Generator, do not modify.
    -->
    insert into t_sys_user (id, user_id, user_name, 
      password, status, create_user_id, 
      update_user_id, create_date, update_date, 
      last_login_date, description, organization_id, 
      user_type, auth_type, emp_entry_time, 
      emp_leave_time, emp_status, tel
      )
    values (#{id,jdbcType=BIGINT}, #{userId,jdbcType=VARCHAR}, #{userName,jdbcType=VARCHAR}, 
      #{password,jdbcType=VARCHAR}, #{status,jdbcType=BIGINT}, #{createUserId,jdbcType=BIGINT}, 
      #{updateUserId,jdbcType=BIGINT}, #{createDate,jdbcType=TIMESTAMP}, #{updateDate,jdbcType=TIMESTAMP}, 
      #{lastLoginDate,jdbcType=TIMESTAMP}, #{description,jdbcType=VARCHAR}, #{organizationId,jdbcType=BIGINT}, 
      #{userType,jdbcType=BIGINT}, #{authType,jdbcType=BIGINT}, #{empEntryTime,jdbcType=TIMESTAMP}, 
      #{empLeaveTime,jdbcType=TIMESTAMP}, #{empStatus,jdbcType=BIGINT}, #{tel,jdbcType=VARCHAR}
      )
  </insert>
  <insert id="insertSelective" parameterType="com.sales.model.system.SysUser">
    <!--
      WARNING - @mbg.generated
      This element is automatically generated by MyBatis Generator, do not modify.
    -->
    insert into t_sys_user
    <trim prefix="(" suffix=")" suffixOverrides=",">
      <if test="id != null">
        id,
      </if>
      <if test="userId != null">
        user_id,
      </if>
      <if test="userName != null">
        user_name,
      </if>
      <if test="password != null">
        password,
      </if>
      <if test="status != null">
        status,
      </if>
      <if test="createUserId != null">
        create_user_id,
      </if>
      <if test="updateUserId != null">
        update_user_id,
      </if>
      <if test="createDate != null">
        create_date,
      </if>
      <if test="updateDate != null">
        update_date,
      </if>
      <if test="lastLoginDate != null">
        last_login_date,
      </if>
      <if test="description != null">
        description,
      </if>
      <if test="organizationId != null">
        organization_id,
      </if>
      <if test="userType != null">
        user_type,
      </if>
      <if test="authType != null">
        auth_type,
      </if>
      <if test="empEntryTime != null">
        emp_entry_time,
      </if>
      <if test="empLeaveTime != null">
        emp_leave_time,
      </if>
      <if test="empStatus != null">
        emp_status,
      </if>
      <if test="tel != null">
        tel,
      </if>
    </trim>
    <trim prefix="values (" suffix=")" suffixOverrides=",">
      <if test="id != null">
        #{id,jdbcType=BIGINT},
      </if>
      <if test="userId != null">
        #{userId,jdbcType=VARCHAR},
      </if>
      <if test="userName != null">
        #{userName,jdbcType=VARCHAR},
      </if>
      <if test="password != null">
        #{password,jdbcType=VARCHAR},
      </if>
      <if test="status != null">
        #{status,jdbcType=BIGINT},
      </if>
      <if test="createUserId != null">
        #{createUserId,jdbcType=BIGINT},
      </if>
      <if test="updateUserId != null">
        #{updateUserId,jdbcType=BIGINT},
      </if>
      <if test="createDate != null">
        #{createDate,jdbcType=TIMESTAMP},
      </if>
      <if test="updateDate != null">
        #{updateDate,jdbcType=TIMESTAMP},
      </if>
      <if test="lastLoginDate != null">
        #{lastLoginDate,jdbcType=TIMESTAMP},
      </if>
      <if test="description != null">
        #{description,jdbcType=VARCHAR},
      </if>
      <if test="organizationId != null">
        #{organizationId,jdbcType=BIGINT},
      </if>
      <if test="userType != null">
        #{userType,jdbcType=BIGINT},
      </if>
      <if test="authType != null">
        #{authType,jdbcType=BIGINT},
      </if>
      <if test="empEntryTime != null">
        #{empEntryTime,jdbcType=TIMESTAMP},
      </if>
      <if test="empLeaveTime != null">
        #{empLeaveTime,jdbcType=TIMESTAMP},
      </if>
      <if test="empStatus != null">
        #{empStatus,jdbcType=BIGINT},
      </if>
      <if test="tel != null">
        #{tel,jdbcType=VARCHAR},
      </if>
    </trim>
  </insert>
  <update id="updateByPrimaryKeySelective" parameterType="com.sales.model.system.SysUser">
    <!--
      WARNING - @mbg.generated
      This element is automatically generated by MyBatis Generator, do not modify.
    -->
    update t_sys_user
    <set>
      <if test="userId != null">
        user_id = #{userId,jdbcType=VARCHAR},
      </if>
      <if test="userName != null">
        user_name = #{userName,jdbcType=VARCHAR},
      </if>
      <if test="password != null">
        password = #{password,jdbcType=VARCHAR},
      </if>
      <if test="status != null">
        status = #{status,jdbcType=BIGINT},
      </if>
      <if test="createUserId != null">
        create_user_id = #{createUserId,jdbcType=BIGINT},
      </if>
      <if test="updateUserId != null">
        update_user_id = #{updateUserId,jdbcType=BIGINT},
      </if>
      <if test="createDate != null">
        create_date = #{createDate,jdbcType=TIMESTAMP},
      </if>
      <if test="updateDate != null">
        update_date = #{updateDate,jdbcType=TIMESTAMP},
      </if>
      <if test="lastLoginDate != null">
        last_login_date = #{lastLoginDate,jdbcType=TIMESTAMP},
      </if>
      <if test="description != null">
        description = #{description,jdbcType=VARCHAR},
      </if>
      <if test="organizationId != null">
        organization_id = #{organizationId,jdbcType=BIGINT},
      </if>
      <if test="userType != null">
        user_type = #{userType,jdbcType=BIGINT},
      </if>
      <if test="authType != null">
        auth_type = #{authType,jdbcType=BIGINT},
      </if>
      <if test="empEntryTime != null">
        emp_entry_time = #{empEntryTime,jdbcType=TIMESTAMP},
      </if>
      <if test="empLeaveTime != null">
        emp_leave_time = #{empLeaveTime,jdbcType=TIMESTAMP},
      </if>
      <if test="empStatus != null">
        emp_status = #{empStatus,jdbcType=BIGINT},
      </if>
      <if test="tel != null">
        tel = #{tel,jdbcType=VARCHAR},
      </if>
    </set>
    where id = #{id,jdbcType=BIGINT}
  </update>
  <update id="updateByPrimaryKey" parameterType="com.sales.model.system.SysUser">
    <!--
      WARNING - @mbg.generated
      This element is automatically generated by MyBatis Generator, do not modify.
    -->
    update t_sys_user
    set user_id = #{userId,jdbcType=VARCHAR},
      user_name = #{userName,jdbcType=VARCHAR},
      <!-- password = #{password,jdbcType=VARCHAR}, -->
      status = #{status,jdbcType=BIGINT},
      <!-- create_user_id = #{createUserId,jdbcType=BIGINT}, -->
      update_user_id = #{updateUserId,jdbcType=BIGINT},
      <!-- create_date = #{createDate,jdbcType=TIMESTAMP}, -->
      update_date = #{updateDate,jdbcType=TIMESTAMP},
      last_login_date = #{lastLoginDate,jdbcType=TIMESTAMP},
      description = #{description,jdbcType=VARCHAR},
      organization_id = #{organizationId,jdbcType=BIGINT},
      user_type = #{userType,jdbcType=BIGINT},
      auth_type = #{authType,jdbcType=BIGINT},
      emp_entry_time = #{empEntryTime,jdbcType=TIMESTAMP},
      emp_leave_time = #{empLeaveTime,jdbcType=TIMESTAMP},
      emp_status = #{empStatus,jdbcType=BIGINT},
      tel = #{tel,jdbcType=VARCHAR}
    where id = #{id,jdbcType=BIGINT}
  </update>
  
   <select id="selectList" resultMap="BaseResultMap"
		parameterType="java.util.Map">
		<!-- WARNING - @mbggenerated This element is automatically generated by 
			MyBatis Generator, do not modify. -->
		select
		<include refid="Base_Column_List" />
		<include refid="Base_From_Tbl" />
		<where>
			<if test="o.id != null">
				<trim prefix="AND (" suffix=")" suffixOverrides="AND | OR">
					o.id = #{o.id}
				</trim>
			</if>
			 <if test="o.userId != null and o.userId != ''">
				<trim prefix="AND (" suffix=")" suffixOverrides="AND | OR">
					o.user_id like CONCAT('%','${o.userId}','%')
				</trim>
			</if>
			<if test="o.userName != null and o.userName != ''">
				<trim prefix="AND (" suffix=")" suffixOverrides="AND | OR">
					o.user_name like CONCAT('%','${o.userName}','%')
				</trim>
			</if>
			<if test="o.password != null">
				o.password = #{o.password,jdbcType=VARCHAR}
			</if>
			<if test="o.status != null">
				o.status = #{o.status,jdbcType=BIGINT}
			</if>
			<if test="o.createUserId != null">
				o.create_user_id = #{o.createUserId,jdbcType=BIGINT}
			</if>
			<if test="o.updateUserId != null">
				o.update_user_id = #{o.updateUserId,jdbcType=BIGINT}
			</if>
			<if test="o.createDate != null">
				o.create_date = #{o.createDate,jdbcType=TIMESTAMP}
			</if>
			<if test="o.updateDate != null">
				o.update_date = #{o.updateDate,jdbcType=TIMESTAMP}
			</if>
			<if test="o.lastLoginDate != null">
				o.last_login_date = #{o.lastLoginDate,jdbcType=TIMESTAMP}
			</if>
			<if test="o.description != null">
				o.description = #{o.description,jdbcType=VARCHAR}
			</if>
			<if test="o.organizationId != null">
				o.organization_id = #{o.organizationId,jdbcType=BIGINT}
			</if>
			<if test="o.userType != null">
				o.user_type = #{o.userType,jdbcType=BIGINT}
			</if>
			<if test="o.authType != null">
				o.auth_type = #{o.authType,jdbcType=BIGINT}
			</if>
			<if test="o.empEntryTime != null">
				o.emp_entry_time = #{o.empEntryTime,jdbcType=TIMESTAMP}
			</if>
			<if test="o.empLeaveTime != null">
				o.emp_leave_time = #{o.empLeaveTime,jdbcType=TIMESTAMP}
			</if>
			<if test="o.empStatus != null">
				o.emp_status = #{o.empStatus,jdbcType=BIGINT}
			</if>
			<if test="o.tel != null">
				o.tel = #{o.tel,jdbcType=VARCHAR}
			</if>
		</where>
	</select>
	
</mapper>